Medienverwaltung: Medium.o Audio.o Bild.o Main.cpp
	g++ Main.cpp Medium.o Audio.o Bild.o -o Medienverwaltung -std=c++11

Medium.o: Medium.h Medium.cpp
	g++ -c Medium.cpp -std=c++11

Audio.o: Audio.h Audio.cpp
	g++ -c Audio.cpp -std=c++11

Bild.o: Bild.h Bild.cpp
	g++ -c Bild.cpp -std=c++11